import { MongoClient } from 'mongodb';
import { randomUUID } from 'crypto';

const URI = 'mongodb+srv://vtual08_db_user:dEdIUU4O3rn6G3ek@cluster0.nws7izg.mongodb.net/kente-couture?retryWrites=true&w=majority&appName=Cluster0';
const DB = 'kente-couture';
const COLL = 'clients';

const now = new Date().toISOString();
const d = (daysFromNow) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + daysFromNow);
  return dt.toISOString().slice(0, 10);
};

const emptyMeasurements = {
  chest: '', waist: '', hips: '', shoulderWidth: '', sleeveLength: '',
  inseam: '', thigh: '', neck: '', height: '', backLength: '',
  frontLength: '', kabaLength: '', waistToKnee: '', underbust: '',
};

const makePayment = (amount, daysAgo) => ({
  id: randomUUID(),
  amount,
  date: d(-daysAgo),
  method: ['Cash', 'MoMo', 'Bank Transfer'][Math.floor(Math.random() * 3)],
  note: '',
});

const clients = [
  {
    id: randomUUID(),
    name: 'Abena Mensah',
    email: 'abena.mensah@gmail.com',
    gender: 'Female',
    dateOfBirth: '1992-04-10',
    phone: '+233 24 456 7890',
    profession: 'Nurse',
    address: 'East Legon, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Wedding',
    eventDate: d(12),
    eventLocation: 'Kempinski Hotel, Accra',
    eventMonth: '',
    kenteVendor: 'Bonwire Kente',
    fabricVendor: '',
    howDidYouHear: 'Instagram',
    referralSource: '',
    comments: '',
    notes: 'Bride — needs 2 kaba & slit sets. Prefers fitted silhouette.',
    fabricNotes: 'Green and gold kente strip fabric confirmed',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '38', waist: '30', hips: '40', height: '165' },
    fittings: {},
    payments: [makePayment(800, 20), makePayment(400, 5)],
    totalCost: 1800,
    timeline: [],
    status: 'Active',
    createdAt: d(-22),
    lastActivity: d(-5),
    startDate: d(-20),
    nextFittingDate: d(3),
    deliveryDate: d(10),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Premium',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Kwame Asante',
    email: 'kwame.asante@yahoo.com',
    gender: 'Male',
    dateOfBirth: '1988-11-22',
    phone: '+233 20 312 5544',
    profession: 'Lawyer',
    address: 'Osu, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Outdoor Naming Ceremony',
    eventDate: d(25),
    eventLocation: 'Labadi Beach Hotel',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: 'Fabric House GH',
    howDidYouHear: 'Referral',
    referralSource: 'Abena Mensah',
    comments: '',
    notes: 'Agbada set — 3 pieces. Embroidery on collar.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '44', waist: '36', hips: '44', height: '178' },
    fittings: {},
    payments: [makePayment(1000, 14)],
    totalCost: 2500,
    timeline: [],
    status: 'Active',
    createdAt: d(-15),
    lastActivity: d(-3),
    startDate: d(-12),
    nextFittingDate: d(7),
    deliveryDate: d(22),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: false,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Standard',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Ama Boateng',
    email: 'ama.boateng@outlook.com',
    gender: 'Female',
    dateOfBirth: '1995-07-03',
    phone: '+233 55 789 0123',
    profession: 'Teacher',
    address: 'Spintex Road, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Traditional Wedding',
    eventDate: d(45),
    eventLocation: 'Kumasi Cultural Centre',
    eventMonth: '',
    kenteVendor: 'Ashanti Kente',
    fabricVendor: '',
    howDidYouHear: 'Facebook',
    referralSource: '',
    comments: '',
    notes: 'Two sets — morning and afternoon wear.',
    fabricNotes: 'Waiting on fabric delivery from Kumasi vendor.',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '36', waist: '28', hips: '38', height: '160' },
    fittings: {},
    payments: [makePayment(500, 10)],
    totalCost: 1400,
    timeline: [],
    status: 'Active',
    createdAt: d(-12),
    lastActivity: d(-2),
    startDate: d(-10),
    nextFittingDate: d(15),
    deliveryDate: d(40),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: false,
    fabricReceived: false,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Standard',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Kofi Darko',
    email: 'kofi.darko@gmail.com',
    gender: 'Male',
    dateOfBirth: '1990-02-14',
    phone: '+233 24 900 1122',
    profession: 'Engineer',
    address: 'Tema, Greater Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Corporate Dinner',
    eventDate: d(8),
    eventLocation: 'Movenpick Ambassador Hotel',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: '',
    howDidYouHear: 'Walk-in',
    referralSource: '',
    comments: '',
    notes: 'Slim fit kente suit. No embroidery.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '42', waist: '34', hips: '42', height: '175' },
    fittings: {},
    payments: [makePayment(1200, 18), makePayment(600, 4)],
    totalCost: 1800,
    timeline: [],
    status: 'Active',
    createdAt: d(-20),
    lastActivity: d(-1),
    startDate: d(-18),
    nextFittingDate: d(2),
    deliveryDate: d(7),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: true,
    noFitting: false,
    delivered: false,
    clientPackage: 'Premium',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Akosua Frimpong',
    email: 'akosua.f@gmail.com',
    gender: 'Female',
    dateOfBirth: '1998-09-17',
    phone: '+233 50 234 5678',
    profession: 'Student',
    address: 'Adenta, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Graduation',
    eventDate: d(30),
    eventLocation: 'University of Ghana, Legon',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: 'Fabric Palace',
    howDidYouHear: 'TikTok',
    referralSource: '',
    comments: '',
    notes: 'Simple kaba & slit. Budget-conscious.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '34', waist: '26', hips: '36', height: '158' },
    fittings: {},
    payments: [makePayment(300, 5)],
    totalCost: 700,
    timeline: [],
    status: 'Active',
    createdAt: d(-6),
    lastActivity: d(-1),
    startDate: d(-5),
    nextFittingDate: d(12),
    deliveryDate: d(27),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: false,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Basic',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Yaw Osei',
    email: 'yaw.osei@hotmail.com',
    gender: 'Male',
    dateOfBirth: '1985-05-30',
    phone: '+233 26 567 8901',
    profession: 'Businessman',
    address: 'Airport Residential, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Anniversary Dinner',
    eventDate: d(60),
    eventLocation: 'La Palm Beach Hotel',
    eventMonth: '',
    kenteVendor: 'Ntonso Adinkra',
    fabricVendor: '',
    howDidYouHear: 'Word of Mouth',
    referralSource: 'Kofi Darko',
    comments: '',
    notes: 'Full kente regalia. Include smock for morning.',
    fabricNotes: 'Adinkra cloth sourced. 6 yards.',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '46', waist: '38', hips: '46', height: '180' },
    fittings: {},
    payments: [makePayment(2000, 30)],
    totalCost: 4500,
    timeline: [],
    status: 'Active',
    createdAt: d(-32),
    lastActivity: d(-4),
    startDate: d(-30),
    nextFittingDate: d(20),
    deliveryDate: d(55),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Luxury',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Efua Quartey',
    email: 'efua.q@gmail.com',
    gender: 'Female',
    dateOfBirth: '1993-12-01',
    phone: '+233 54 321 0987',
    profession: 'Doctor',
    address: 'Cantonments, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Baby Shower',
    eventDate: d(18),
    eventLocation: 'Private Residence, Cantonments',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: 'Kumasi Textiles',
    howDidYouHear: 'Instagram',
    referralSource: '',
    comments: '',
    notes: 'Free-size maternity kaba. Expandable waist.',
    fabricNotes: 'Ankara fabric, blue print.',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '40', waist: '36', hips: '42', height: '163' },
    fittings: {},
    payments: [makePayment(600, 8), makePayment(200, 1)],
    totalCost: 950,
    timeline: [],
    status: 'Active',
    createdAt: d(-9),
    lastActivity: d(-1),
    startDate: d(-8),
    nextFittingDate: d(5),
    deliveryDate: d(16),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Standard',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Nana Ama Tetteh',
    email: 'nana.tetteh@gmail.com',
    gender: 'Female',
    dateOfBirth: '1991-03-25',
    phone: '+233 27 111 2233',
    profession: 'Banker',
    address: 'Dzorwulu, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'End-of-Year Party',
    eventDate: d(2),
    eventLocation: 'Alisa Hotel, Accra',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: '',
    howDidYouHear: 'Referral',
    referralSource: '',
    comments: '',
    notes: 'Off-shoulder kaba. Gold accessories.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '37', waist: '29', hips: '39', height: '162' },
    fittings: {},
    payments: [makePayment(800, 15), makePayment(400, 7), makePayment(400, 1)],
    totalCost: 1600,
    timeline: [],
    status: 'Active',
    createdAt: d(-18),
    lastActivity: d(-1),
    startDate: d(-15),
    nextFittingDate: '',
    deliveryDate: d(1),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: true,
    noFitting: false,
    delivered: false,
    clientPackage: 'Premium',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Kweku Adjei',
    email: 'kweku.adjei@gmail.com',
    gender: 'Male',
    dateOfBirth: '1996-08-08',
    phone: '+233 23 445 6677',
    profession: 'Photographer',
    address: 'Madina, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Family Reunion',
    eventDate: d(50),
    eventLocation: 'Boti Falls, Eastern Region',
    eventMonth: '',
    kenteVendor: 'Bonwire Kente',
    fabricVendor: '',
    howDidYouHear: 'Word of Mouth',
    referralSource: '',
    comments: '',
    notes: 'Group order — 3 kente shirts (same fabric, different sizes for him and brothers).',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '40', waist: '32', hips: '40', height: '172' },
    fittings: {},
    payments: [makePayment(450, 3)],
    totalCost: 1350,
    timeline: [],
    status: 'Active',
    createdAt: d(-4),
    lastActivity: d(-1),
    startDate: d(-3),
    nextFittingDate: d(20),
    deliveryDate: d(46),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: false,
    measurementsTaken: false,
    fabricReceived: false,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Standard',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Serwa Amponsah',
    email: 'serwa.amp@gmail.com',
    gender: 'Female',
    dateOfBirth: '1989-06-12',
    phone: '+233 24 667 8899',
    profession: 'Lecturer',
    address: 'Ashale Botwe, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Outdooring',
    eventDate: d(1),
    eventLocation: 'Private Home, Accra',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: 'Accra Fashion Mall',
    howDidYouHear: 'Facebook',
    referralSource: '',
    comments: '',
    notes: 'Church outfit. Modest neckline. Lace fabric.',
    fabricNotes: 'Champagne lace — 4 yards delivered.',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '38', waist: '31', hips: '40', height: '164' },
    fittings: {},
    payments: [makePayment(700, 12), makePayment(500, 2)],
    totalCost: 1200,
    timeline: [],
    status: 'Active',
    createdAt: d(-13),
    lastActivity: d(-2),
    startDate: d(-12),
    nextFittingDate: '',
    deliveryDate: d(0),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: true,
    noFitting: false,
    delivered: false,
    clientPackage: 'Standard',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Fiifi Poku',
    email: 'fiifi.poku@gmail.com',
    gender: 'Male',
    dateOfBirth: '1987-01-19',
    phone: '+233 57 334 5566',
    profession: 'Architect',
    address: 'Ridge, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Work Anniversary Gala',
    eventDate: d(-5),
    eventLocation: 'Marriott Hotel Accra',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: '',
    howDidYouHear: 'Instagram',
    referralSource: '',
    comments: '',
    notes: 'Kente bow-tie and pocket square set with matching shirt.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '43', waist: '35', hips: '43', height: '177' },
    fittings: {},
    payments: [makePayment(900, 25), makePayment(900, 8)],
    totalCost: 1800,
    timeline: [],
    status: 'Completed',
    createdAt: d(-30),
    lastActivity: d(-5),
    startDate: d(-28),
    nextFittingDate: '',
    deliveryDate: d(-5),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: true,
    noFitting: false,
    delivered: true,
    clientPackage: 'Premium',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Adwoa Owusu',
    email: 'adwoa.owusu@gmail.com',
    gender: 'Female',
    dateOfBirth: '2000-10-05',
    phone: '+233 20 778 9900',
    profession: 'Model',
    address: 'North Labone, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Fashion Show',
    eventDate: d(-10),
    eventLocation: 'National Theatre, Accra',
    eventMonth: '',
    kenteVendor: 'Kente Village',
    fabricVendor: '',
    howDidYouHear: 'TikTok',
    referralSource: '',
    comments: '',
    notes: 'High-end editorial kente gown. Full-length.',
    fabricNotes: 'Kente strip woven — designer pattern.',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '33', waist: '24', hips: '35', height: '170' },
    fittings: {},
    payments: [makePayment(2500, 40), makePayment(2500, 12)],
    totalCost: 5000,
    timeline: [],
    status: 'Completed',
    createdAt: d(-45),
    lastActivity: d(-10),
    startDate: d(-42),
    nextFittingDate: '',
    deliveryDate: d(-11),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: true,
    noFitting: false,
    delivered: true,
    clientPackage: 'Luxury',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Esi Antwi',
    email: 'esi.antwi@gmail.com',
    gender: 'Female',
    dateOfBirth: '1994-02-28',
    phone: '+233 24 556 7788',
    profession: 'Nurse',
    address: 'Achimota, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Church Programme',
    eventDate: d(-2),
    eventLocation: 'Perez Chapel International',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: 'Kantamanto Market',
    howDidYouHear: 'Referral',
    referralSource: 'Efua Quartey',
    comments: '',
    notes: 'Two-piece blouse and skirt. Purple and white.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '36', waist: '29', hips: '38', height: '161' },
    fittings: {},
    payments: [makePayment(550, 14), makePayment(250, 3)],
    totalCost: 800,
    timeline: [],
    status: 'Completed',
    createdAt: d(-16),
    lastActivity: d(-2),
    startDate: d(-14),
    nextFittingDate: '',
    deliveryDate: d(-3),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: false,
    noFitting: true,
    delivered: true,
    clientPackage: 'Basic',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Kwabena Amoah',
    email: 'kwabena.amoah@gmail.com',
    gender: 'Male',
    dateOfBirth: '1983-07-07',
    phone: '+233 26 990 0011',
    profession: 'Civil Servant',
    address: 'Kasoa, Central Region',
    state: 'Central',
    country: 'Ghana',
    eventName: 'Funeral',
    eventDate: d(-20),
    eventLocation: 'Kasoa Township',
    eventMonth: '',
    kenteVendor: '',
    fabricVendor: '',
    howDidYouHear: 'Walk-in',
    referralSource: '',
    comments: '',
    notes: 'Black cloth outfit. Simple senator style.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements, chest: '48', waist: '42', hips: '50', height: '174' },
    fittings: {},
    payments: [makePayment(600, 30)],
    totalCost: 600,
    timeline: [],
    status: 'Archived',
    createdAt: d(-35),
    lastActivity: d(-20),
    startDate: d(-32),
    nextFittingDate: '',
    deliveryDate: d(-21),
    assignedWorker: '',
    productionNotes: [],
    consultationDone: true,
    measurementsTaken: true,
    fabricReceived: true,
    fittingDone: false,
    noFitting: true,
    delivered: true,
    clientPackage: 'Basic',
    updatedAt: now,
  },
  {
    id: randomUUID(),
    name: 'Maame Serwaa',
    email: 'maame.serwaa@gmail.com',
    gender: 'Female',
    dateOfBirth: '1997-04-22',
    phone: '+233 55 100 2020',
    profession: 'Content Creator',
    address: 'East Legon Hills, Accra',
    state: 'Greater Accra',
    country: 'Ghana',
    eventName: 'Engagement Party',
    eventDate: d(90),
    eventLocation: 'Private Villa, Trasacco',
    eventMonth: '',
    kenteVendor: 'Bonwire Premium',
    fabricVendor: '',
    howDidYouHear: 'Instagram',
    referralSource: '',
    comments: '',
    notes: 'Bridal consultation only — full order pending fabric selection.',
    fabricNotes: '',
    clientPhoto: '',
    fabricPhotos: [],
    clientPhotos: [],
    illustrations: [],
    fabrics: [],
    measurements: { ...emptyMeasurements },
    fittings: {},
    payments: [],
    totalCost: 3200,
    timeline: [],
    status: 'Active',
    createdAt: d(-1),
    lastActivity: d(-1),
    startDate: '',
    nextFittingDate: '',
    deliveryDate: '',
    assignedWorker: '',
    productionNotes: [],
    consultationDone: false,
    measurementsTaken: false,
    fabricReceived: false,
    fittingDone: false,
    noFitting: false,
    delivered: false,
    clientPackage: 'Luxury',
    updatedAt: now,
  },
];

const mongoClient = new MongoClient(URI);

try {
  await mongoClient.connect();
  const db = mongoClient.db(DB);
  const col = db.collection(COLL);

  // Use bulkWrite with upsert to avoid duplicates on re-run
  const ops = clients.map(c => ({
    updateOne: {
      filter: { id: c.id },
      update: { $setOnInsert: c },
      upsert: true,
    },
  }));

  const result = await col.bulkWrite(ops);
  console.log(`Seeded: ${result.upsertedCount} inserted, ${result.matchedCount} already existed.`);
} finally {
  await mongoClient.close();
}
